baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"

  themeColor = "orange"

  showMenuItems = 2

  showLanguageSelector = false

  fullWidthTheme =  false

  centerTheme = true

  showLastUpdated = false


[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "FoodDiary Live"
    subtitle = "Live Food Journey"
    owner = "kd puvvadi"
    keywords = ""
    copyright = "kd puvvadi"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "FoodDiary Live"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/"
      
